# fly.toml app configuration file generated for dating-application on 2023-09-04T15:34:31+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "dating-application"
primary_region = "otp"

[build]
  image = "vitalienanu/datingapp:latest"

[env]
  ASPNETCORE_URLS="http://+:8080"
  CloudinarySettings__CloudName="dldofp4ti"
  CloudinarySettings__ApiKey="652719593548541"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
